[build]
  command = "python -m pip install -r requirements.txt"
  functions = "functions"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200